name = "leads-api"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
tail_consumers = [{ service = "alert-worker" }]

[triggers]
crons = ["*/5 * * * *"]
[[kv_namespaces]]
binding = "LEADS_SYNC_CONFIG"
id = "352dc4a8e9244b88b315a12590fd6a1a"
[[kv_namespaces]]
binding = "LEADS_SYNC_CACHE"
id = "5bdb23b812e54e0fbd9b70dfa25cd5db"
